/* 顶部菜单栏 */
export const MAIN_HEADER_SELECTED_ITEM = 'MAIN_HEADER_SELECTED_ITEM'
/* 侧边栏 */
export const MAIN_SIDEBAR_SIDE_ITEM = 'MAIN_SIDEBAR_SIDE_ITEM'
export const MAIN_SIDEBAR_SEARCH_ENABLED = 'MAIN_SIDEBAR_SEARCH_ENABLED'
export const MAIN_SIDEBAR_MENU_ENABLED = 'MAIN_SIDEBAR_MENU_ENABLED'
export const MAIN_SIDEBAR_SELECTED_ITEM = 'MAIN_SIDEBAR_SELECTED_ITEM'

/* 窗口对应的标签 */
export const WINDOW_TAB_CREATEITEM = 'WINDOW_TAB_CREATEITEM'
export const WINDOW_TAB_DESTROYITEM = 'WINDOW_TAB_DESTROYITEM'
export const WINDOW_TAB_CHANGEITEM = 'WINDOW_TAB_CHANGEITEM'
export const WINDOW_TAB_CLEAR = 'WINDOW_TAB_CLEAR'
